### ISSUE TITLE
Stats for more repos

### ISSUE THREAD

**Issue by johan-bjareholt** [ActivityWatch/contributor-stats#3]
- thankful
- aw-client-js

perhaps also

- aw-client-rust?
- aw-watcher-vim?

**Comment by ErikBjare** [comment]
Done in https://github.com/ActivityWatch/contributor-stats/commit/26c901873dae76450bdc54f6c2f038d4348d8810 and https://github.com/ActivityWatch/activitywatch.github.io/commit/3b98fa95f166751ba793393d01abebff39ea5a39
